apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "titanic-api.fullname" . }}-db
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "titanic-api.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              name: prod
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: postgres
      ports:
        - protocol: TCP
          port: 5432
